### ISSUE TITLE
Testing bca-webtools outside of Vagrant

### ISSUE THREAD

**Issue by zvowell** [BitCurator/bca-webtools#14]
I'm trying to make sure that I have all of the bca-webtools software and dependencies in place in a specific environment. Here are the details of the OS that I'm installing on:

Distributor ID: Ubuntu
Description:    Ubuntu 12.04.5 LTS
Release:        12.04
Codename:    precise

The installation of dependencies went pretty smooth, but here's some notes:
-I could only get postgresql-server-dev-9.1 instead of postgresql-server-dev-9.3
-With the dependencies installed, I cloned into the bca-webtools repo from /usr/local/bin
-Then I ran 'python runserver.py' and got a message saying the server's running on http://0.0.0.0:5000

But from there, I'm stumped. Is there a way from this point where I can test whether the bca-webtools application is working properly? Do I need to forward the port for web access (which seems to be done in the Vagrantfile if I were using vagrant)?

Thanks!

Zach

**Comment by kamwoods** [comment]
Hi Zach,

We're working on a major update, currently, and the build instructions for
non-Vagrant use are a bit out of date right now. The default build of
bca-webtools currently only works out-of-the-box when using Vagrant.
Deploying directly to a machine requires some additional configuration
(e.g., where the disk images are being stored) by modifying the Python code
itself. The next version should eliminate these hardcoded locations.
Updates coming soon...

Regards,

Kam

**Comment by zvowell** [comment]
Hi Kam,
That's exciting, looking forward to the update! If you need anyone to help test, let me know. We were able to get the current version running well in Vagrant, which is what inspired me to try it out elsewhere.

The whole question of where the disk images are stored is definitely something we're trying to figure out as well. I believe other Islandora viewers grab a URL location of the specific datastream that they will display, so that we'll likely need to define a method for dynamically locating the disk images for bca-webtools.

Thanks again!
Zach
